# Generated by Django 2.2 on 2021-01-19 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organiztions', '0002_auto_20210119_1009'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organiztions.CourseOrg', verbose_name='课程机构'),
        ),
    ]
